"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function RegisterPage() {
  const [username,setUsername]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const supabase=createClient();const {data:existing}=await supabase.from("profiles").select("id").eq("username",username.trim().toLowerCase()).maybeSingle();if(existing){setError("That username is already taken.");setBusy(false);return}const {error:authError}=await supabase.auth.signUp({email,password,options:{data:{username:username.trim().toLowerCase()}}});if(authError){setError(authError.message);setBusy(false);return}window.location.href="/onboarding";}
  return <div className="auth-shell"><section className="auth-visual"><div className="auth-orb"/><span className="snap-eyebrow">SNITCHGRAM / JOIN</span><h1>Make your<br/><span style={{color:'#fffc00'}}>own signal.</span></h1><p>Create a real account and start building your place in the social graph. Your username becomes your identity.</p></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="auth-brand"><i><Sparkles size={18}/></i><span>SNITCHGRAM</span></div><div style={{marginTop:26}}><div className="snap-eyebrow">CREATE ACCOUNT</div><h2>Enter the world.</h2><p className="sub">No bots. No fake identities.</p></div><label>Username<input required value={username} onChange={e=>setUsername(e.target.value.replace(/\s/g,''))} minLength={3} maxLength={24} placeholder="yourname" autoComplete="username"/></label><label style={{display:'block',marginTop:14}}>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label style={{display:'block',marginTop:14}}>Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8+ characters" autoComplete="new-password"/></label>{error&&<p style={{color:'#ff7c7c',fontSize:11,marginTop:12}}>{error}</p>}<button className="btn btn-primary" disabled={busy} style={{width:'100%',marginTop:18,display:'flex',justifyContent:'center',alignItems:'center',gap:8}}>{busy?'Creating…':<>Create account <ArrowRight size={16}/></>}</button><p className="auth-footer">Already here? <Link href="/login">Sign in</Link></p></form></section></div>;
}
